### ISSUE TITLE
getting nothing terminal window after running setup

### ISSUE THREAD

**Issue by Piyushchauhan1999** [tapparelj/gr-lora_sdr#75]
Setup Done
![Screenshot from 2024-01-18 17-28-40](https://github.com/tapparelj/gr-lora_sdr/assets/83907036/a172f2de-858c-4da2-9b82-e120e4807c5f)
Output Getting

![Screenshot from 2024-01-18 17-30-36](https://github.com/tapparelj/gr-lora_sdr/assets/83907036/41a8d320-b092-4af1-a34f-f53bc5e08bf1)

**Comment by Piyushchauhan1999** [comment]
physical setup
![WhatsApp Image 2024-01-18 at 5 32 41 P
signal received
![Screenshot from 2024-01-18 17-43-42](https://github.com/tapparelj/gr-lora_sdr/assets/83907036/1a26de79-ae2a-4637-8dc1-fb39d46de8c8)
M](https://github.com/tapparelj/gr-lora_sdr/assets/83907036/43515708-d898-44ba-88aa-977b7d56a901)

**Comment by Piyushchauhan1999** [comment]
signal Revived
![Screenshot from 2024-01-18 17-43-42](https://github.com/tapparelj/gr-lora_sdr/assets/83907036/5580a335-f624-49e5-a616-b0902d8ee6c9)

**Comment by tapparelj** [comment]
Hi @Piyushchauhan1999,
first question to see if the installation went correctly: is the flowgraph tx_rx_functionnality_check.py working?

**Comment by Piyushchauhan1999** [comment]
![Screenshot from 2024-01-18 17-47-55](https://github.com/tapparelj/gr-lora_sdr/assets/83907036/2914b98b-bda4-43c7-b646-08bc481b9d91)
I think its fine

**Comment by tapparelj** [comment]
Good, then it's easy to have some mismatch of configuration between the commercial transmitter and the receiver. 
Here are a come things to double check:
- the Tx center freq and bandwidth (seems ok from your plot)
- the sync word (sometime called network identifiers): here the receiver expect 0x12, that value needs to match what the transmitter is set to use.
I noticed that you use a quite high sampling rate. I've never used such a large oversampling factor so I would try using a sampling rate much smaller to avoid picking up a lot of out-of-band noise (e.g. 1MHz -> os_factor = 4).

Some hex values are printed in the terminal, you changed the code to print them or you use a different branch than the master?

If you have a spare hackrf, using them for transmitting and receiving may help to identify if the issue comes from the LoRa chip config or the gnuradio one.

**Comment by tapparelj** [comment]
this is very strange. 
Can you try to see if the transmitted frame seems strange? 
As example on my side using cubicSDR (easy to install with just apt install) if I set the SF to 12 and use a simple setup with two LimeSDR Mini, I'm able to clearly see the transmitted chirps as:
![image](https://github.com/tapparelj/gr-lora_sdr/assets/66671413/1e0ca725-b9c5-4116-9922-61ca8b3ee202)

**Comment by Piyushchauhan1999** [comment]
with sf 7 i am not getting any timeout 
![Screenshot from 2024-01-19 11-06-04](https://github.com/tapparelj/gr-lora_sdr/assets/83907036/cbf8786e-fcb7-4874-a3a5-255fa5b4858d)
but with sf12 i am getting  timeout
![Screenshot from 2024-01-19 11-11-49](https://github.com/tapparelj/gr-lora_sdr/assets/83907036/cca8bc85-f8f0-4ba8-9f6f-90341851fac9)

**Comment by tapparelj** [comment]
I've never used a Hack RF One but it seems that they don't recommend to use a sampling rate lower than 8MHz (based on [this](https://hackrf.readthedocs.io/en/latest/sampling_rate.html)), but to decimate and filter after the soapy source in gnuradio.

Are the timeout showing up at regular time interval? If the time interval corresponds to the period between frames, this is caused by the flowgraph not generating constantly samples, but only for a frame (there is a tag present in the stream that fixes this "issue" for the UHD USRP sink, but I don't see a similar option for the soapy hackrf sink)

Even with the error, are you able to get a trace of what you are transmitting?

**Comment by Piyushchauhan1999** [comment]
this is a real lora transmission from a lora device that my blade rf is able capture
![Screenshot from 2024-01-19 15-43-27](https://github.com/tapparelj/gr-lora_sdr/assets/83907036/c7e23c61-0d0a-4182-817a-c4f509e3c6e6)
and i am getting this error in No gui mode

![Screenshot from 2024-01-19 15-41-13](https://github.com/tapparelj/gr-lora_sdr/assets/83907036/c9af27ae-e311-460d-bd84-a4e7dcec485e)

**Comment by Piyushchauhan1999** [comment]
can you send me the details of the sdr that you are using its name model and settings you are using with its specific firmware and if you can provide link or provider from where or whom you have purchased it

**Comment by tapparelj** [comment]
The error you get is caused by having a buffer too small between the Soapy source and the frame sync. You can fix it by setting the _minoutbuf_ parameter of the soapy source (under the Advanced tab) to something like : int(np.ceil(samp_rate/bw*(2**sf+2))).

As SDR receivers, I've used:
- NI USRP-2920
- USRP B200mini
- LimeSDR USB
- LimeSDR Mini
For the RF settings, I mostly use 125kHz bandwidth, 500kHz sampling rate and a carrier frequency of 868.1MHz

**Comment by Piyushchauhan1999** [comment]
Hey tapparelj,
I was looking to buy LimeSDR Mini. But Lime SDR USB and LimeSDR Mini have been discontinued. The RF parameter for LimeSDR Mini 2.0 is same as LimeSDR Mini. Have you tested LimeSDR Mini 2.0?

**Comment by tapparelj** [comment]
I don't have a LimeSDR Mini 2.0 unfortunately, but they still use the same RF chip LMS7002M so they should not behave differently.

**Comment by Piyushchauhan1999** [comment]
Hello,
I have purchased a LimeSDR mini 2.0 but still I'm not able to get the results 
![Screenshot from 2024-03-06 15-54-24](https://github.com/tapparelj/gr-lora_sdr/assets/83907036/df2ce9b7-d97d-43ac-b7dc-f1d3d505b7a5)

**Comment by Piyushchauhan1999** [comment]
When using LoRa Rx block I was able to get the result 
![Screenshot from 2024-03-06 16-55-42](https://github.com/tapparelj/gr-lora_sdr/assets/83907036/0b935198-88e7-4d9a-8213-10f5418a7902)
But If if keep the Implicit header to NO keeping the payload length and coding rate same I was not able to get the results
![Screenshot from 2024-03-06 16-55-42](https://github.com/tapparelj/gr-lora_sdr/assets/83907036/87d43c8f-a522-4fac-a389-5093971a332b)

**Comment by Piyushchauhan1999** [comment]
also the LoRa Rx block with implicit Header = NO is not working for sf 5 and sf 6
