### ISSUE TITLE
GNU Radio3.8.3.1

### ISSUE THREAD

**Issue by G55366** [tapparelj/gr-lora_sdr#86]
May I ask how to deploy this project to an older version of gnuradio, such as gnuradio 3.8.3.1

**Comment by tapparelj** [comment]
Hello @G55366,
to port to a previous version of gnuradio, I would do the following
- Create a OOT module from scratch in your 3.8 install.
- Name it lora_sdr (to generate an OOT module that will have the same name as this one)
- Copy the code from the gr-lora_sdr/lib, gr-lora_sdr/grc and gr-lora_sdr/include in the new module you created
- Add the files names in the CMakeLists.txt (You can generate a dummy block to have a reference on how you should modify the cmakelists)
- Then, it's a matter of seeing what error you get while compiling and try fixing anything that pops up.
- Looking at the gnuradio wiki information about porting modules to newer version may give some ideas of what was changed between versions (for example use boost::sptr instead of std::sptr, the way of declaring message callbacks,  etc...)

As you can tell it is not the most practical procedure, but it's the cleanest way I see. If you go through this and have a working version, I would be happy to create a new branch for this updated 3.8 version such that other people in your case can also benefit from it! 

In any case, let me know if you encounter some errors you don't see how to fix. I'll be happy to help!

**Comment by G55366** [comment]
Thank you very much for your help

**Comment by tapparelj** [comment]
Hello, I'll close this issue for now. 
Don't hesitate to reopen it if needed.
